title: Tyler Wang
site-title: Drawings in Sand
subtitle: >- # this means to ignore newlines until "baseurl:"
  Story of Tyler Wang
description: >- # this means to ignore newlines until "baseurl:"
  Tyler Wang is a student at the University of Illinois Urbana-Champaign studying Physics and Mathematics.
baseurl: "" # add /blog
url: "https://tylerwang.org/" # the base hostname & protocol for your site, e.g. http://example.com

lang: en

email: wangtyler123@gmail.com
name: "Tyler Wang"
about: >-
  University of Illinois Urbana-Champaign <br>
  Mathematics BSLAS <br>
  Physics BS <br>
social:
  github: tylerwwang
  linkedin: "https://www.linkedin.com/in/tyler-wang-472261213/"

# Build settings
markdown: kramdown
timezone: America/Chicago
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      type: "posts"
    values:
      layout: "posts"
      author: "Tyler Wang"
      permalink: /posts/:year/:month/:day/:title/
      comments: false
      tex: true
      theorem: true

sass:
  sass_dir: _sass
  style: compressed

google_analytics: "G-MLGCGVFJLC"

menu-pages:
  - "about"
  - "blog"
  - "personal"
